### PR TITLE
chore: use crawler

### PR DESCRIPTION
**Pull request by stefanomunarini**

### CODE REVIEW

**Comment by kesara** [comment]
@stefanomunarini Can you outline the architecture of this new implementation?

**Comment by stefanomunarini** [comment]
Hi @kesara . I can point you to [this issue](https://github.com/relaton/support/issues/4) where you should be able to find the information you're looking for. Feel free to reopen the issue posting any question/doubt you might have.

**Comment by stefanomunarini** [comment]
Please wait to merge this until I assign the PR @kesara . Thanks

**Comment by kesara** [comment]
> Please wait to merge this until I assign the PR @kesara . Thanks

Okay, I'll wait until you assign them to me.
To avoid confusion better to [change these PRs to drafts](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft).
Thanks.

**Review by kesara — APPROVED** [review]

**Pull request merged**
